version: 2.1

executors:
  default:
    working_directory: ~/web-boilerplate
    docker:
      - image: circleci/node:16.13.0

caches:
  - &npm_cache web-boilerplate-v1-{{ checksum "package-lock.json" }}

commands:
  defaults:
    steps:
      - checkout
      - restore_cache:
          key: *npm_cache
      - run:
          name: Installing Dependencies
          command: npm i
      - save_cache:
          key: *npm_cache
          paths:
            - ./node_modules

  linters:
    steps:
      - run:
          name: Running linters
          command: npm run lint
  tests:
    steps:
      - run:
          name: Running tests
          command: npm run test --coverage --maxWorkers=1

jobs:
  linters:
    executor: default
    steps:
      - defaults
      - linters
  tests:
    executor: default
    steps:
      - defaults
      - tests

workflows:
  version: 2.1
  main:
    jobs:
      - linters
      - tests:
          requires:
            - linters
